version: "3.8"

services:
  # MariaDB database
  db:
    image: mariadb:11
    container_name: hitster-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: hitster_user
      MARIADB_PASSWORD: hitster_password
      MARIADB_DATABASE: hitster
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/

  frontend:
    build: ./frontend
    container_name: hitster-frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend

  # Express backend
  backend:
    build: ./backend
    container_name: hitster-backend
    restart: always
    ports:
      - "3003:3003"
    environment:
      DB_HOST: db
      DB_USER: hitster_user
      # make sure this matches the password created during DB init
      DB_PASSWORD: hitster_password
      DB_NAME: hitster
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - db

volumes:
  db_data: