
const styles = {
  bg: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #0a0a14 0%, #150a25 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Georgia, serif",
  },
  startCard: {
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(245,197,24,0.15)",
    borderRadius: 24,
    padding: "56px 48px",
    maxWidth: 420,
    width: "90%",
    textAlign: "center",
  },
  startIcon: { fontSize: 52, marginBottom: 10 },
  startTitle: { fontSize: 48, fontWeight: 900, color: "#f5c518", letterSpacing: 8, marginBottom: 6 },
  startSub: { color: "#666", fontSize: 14, marginBottom: 28, lineHeight: 1.7 },
  playerCountRow: {
    display: "flex",
    gap: 10,
    justifyContent: "center",
    marginBottom: 20,
  },
  countBtn: {
    width: 48,
    height: 48,
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "transparent",
    color: "#666",
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
  },
  countBtnActive: {
    border: "1px solid #f5c518",
    background: "rgba(245,197,24,0.1)",
    color: "#f5c518",
  },
  input: {
    width: "100%",
    padding: "13px 18px",
    borderRadius: 10,
    border: "1px solid rgba(245,197,24,0.25)",
    background: "rgba(255,255,255,0.05)",
    color: "#fff",
    fontSize: 15,
    marginBottom: 10,
    outline: "none",
    fontFamily: "Georgia, serif",
    boxSizing: "border-box",
  },
  primaryBtn: {
    padding: "13px 28px",
    background: "#f5c518",
    color: "#000",
    border: "none",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 800,
    letterSpacing: 1.5,
    cursor: "pointer",
    width: "100%",
    marginBottom: 10,
  },
  highscoreBtn: {
    padding: "11px 28px",
    background: "transparent",
    color: "#f5c518",
    border: "1px solid rgba(245,197,24,0.3)",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  },
  ghostBtn: {
    padding: "13px 28px",
    background: "transparent",
    color: "#666",
    border: "1px solid #333",
    borderRadius: 10,
    fontSize: 14,
    cursor: "pointer",
  },
  hsTable: { marginBottom: 24, textAlign: "left" },
  hsHeader: {
    display: "flex",
    padding: "8px 12px",
    color: "#555",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
    marginBottom: 4,
  },
  hsRow: {
    display: "flex",
    alignItems: "center",
    padding: "10px 12px",
    borderRadius: 8,
    fontSize: 14,
    gap: 4,
  },
  hsRowFirst: {
    background: "rgba(245,197,24,0.06)",
    border: "1px solid rgba(245,197,24,0.15)",
  },
  resultPlayerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderRadius: 10,
    border: "1px solid",
    marginBottom: 8,
  },
  gameBg: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #0a0a14 0%, #150a25 100%)",
    fontFamily: "Georgia, serif",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 28px",
    borderBottom: "1px solid rgba(245,197,24,0.1)",
    background: "rgba(0,0,0,0.4)",
  },
  headerLogo: { color: "#f5c518", fontSize: 20, fontWeight: 900, letterSpacing: 4 },
  playerBar: {
    display: "flex",
    gap: 8,
    padding: "10px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    flexWrap: "wrap",
  },
  playerChip: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 14px",
    borderRadius: 20,
    border: "1px solid",
    transition: "all 0.2s",
  },
  turnBanner: {
    padding: "8px 16px",
    borderLeft: "3px solid",
    margin: "10px 16px",
    borderRadius: 4,
    fontSize: 14,
  },
  timelineWrapper: {
    overflowX: "auto",
    padding: "20px 16px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  timelineScroll: {
    display: "flex",
    alignItems: "center",
    minWidth: "max-content",
    position: "relative",
    paddingBottom: 4,
  },
  timelineLine: {
    position: "absolute",
    top: "50%",
    left: 0,
    right: 0,
    height: 1,
    background: "rgba(245,197,24,0.1)",
    transform: "translateY(-50%)",
    zIndex: 0,
    pointerEvents: "none",
  },
  slot: {
    width: 44,
    height: 110,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    zIndex: 1,
  },
slotInner: {
  width: 36,
  height: 36,
  borderRadius: "50%",
  border: "2px dashed rgba(245,197,24,0.4)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "rgba(245,197,24,0.4)",
  fontSize: 20,
  fontWeight: 700,
  transition: "all 0.15s",
},
  slotInnerActive: {
    background: "rgba(245,197,24,0.1)",
    transform: "scale(1.2)",
  },
  slotActive: {},
  tlCard: {
    background: "linear-gradient(160deg, #1c1c35 0%, #251540 100%)",
    border: "1px solid",
    borderRadius: 12,
    padding: "14px 16px",
    minWidth: 120,
    maxWidth: 140,
    flexShrink: 0,
    textAlign: "center",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 4px 16px rgba(0,0,0,0.3)",
    zIndex: 1,
    margin: "0 4px",
  },
  tlCardStripe: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  tlCardYear: { fontSize: 22, fontWeight: 900, marginBottom: 6, marginTop: 4 },
  tlCardTitle: { color: "#fff", fontSize: 11, fontWeight: 700, marginBottom: 3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  tlCardArtist: { color: "#777", fontSize: 10, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", marginBottom: 4 },
  tlCardGenre: { color: "rgba(245,197,24,0.5)", fontSize: 9, fontStyle: "italic", textTransform: "uppercase", letterSpacing: 0.5 },
  center: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
  },

  hint: { 
    color: "#aaa", 
    fontSize: 15, 
    marginBottom: 20, 
    letterSpacing: 0.5 
    },

  playCard: {
    borderRadius: 16,
    padding: "32px 40px",
    width: 240,
    textAlign: "center",
    cursor: "grab",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
    userSelect: "none",
  },
  playCardBadge: { fontSize: 48, fontWeight: 900, color: "rgba(0,0,0,0.15)", marginBottom: 10, lineHeight: 1 },
  playCardTitle: { fontSize: 19, fontWeight: 900, color: "#000", marginBottom: 5, lineHeight: 1.2 },
  playCardArtist: { fontSize: 13, color: "rgba(0,0,0,0.55)", marginBottom: 12 },
  playCardDivider: { height: 1, background: "rgba(0,0,0,0.1)", marginBottom: 10 },
  playCardGenre: { fontSize: 11, color: "rgba(0,0,0,0.4)", fontStyle: "italic", textTransform: "uppercase", letterSpacing: 1 },
  feedbackBox: {
    border: "1px solid",
    borderRadius: 16,
    padding: "28px 36px",
    textAlign: "center",
    maxWidth: 400,
    width: "90%",
  },
  trash: {
    borderTop: "1px solid rgba(233,69,96,0.15)",
    padding: "12px 24px",
    background: "rgba(233,69,96,0.03)",
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    flexWrap: "wrap",
  },
  trashTitle: { color: "#e94560", fontSize: 12, fontWeight: 700, whiteSpace: "nowrap", paddingTop: 4 },
  trashList: { display: "flex", gap: 8, flexWrap: "wrap" },
  trashChip: {
    background: "rgba(233,69,96,0.08)",
    border: "1px solid rgba(233,69,96,0.2)",
    borderRadius: 20,
    padding: "3px 12px",
    fontSize: 12,
    color: "#bbb",
  },
  resultRow: {
    display: "flex",
    alignItems: "center",
    padding: "6px 0",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    fontSize: 13,
    gap: 4,
  },
  modalOverlay: {
  position: "fixed",
  top: 0, left: 0, right: 0, bottom: 0,
  background: "rgba(0,0,0,0.7)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  zIndex: 100,
},
modal: {
  background: "#1c1c35",
  border: "1px solid rgba(233,69,96,0.3)",
  borderRadius: 16,
  padding: "32px 40px",
  textAlign: "center",
  maxWidth: 320,
  width: "90%",
},

endBtn: {
  padding: "8px 16px",
  background: "transparent",
  color: "#ccc",
  border: "1px solid #555",
  borderRadius: 8,
  fontSize: 14,
  cursor: "pointer",
},

};

export default styles;